console.log(`Init.js`)
console.log(`Init2.js`)
console.log(`xxxx?.js`)
console.log(`whatsss!`)
console.log(`pull?.js`)
console.log(`conflic!`)
console.log(`new master`)
console.log(`feature A!`)
console.log(`adding a PR`)
console.log(`adding a PR number two!`)
